#============================================================================================================
#                                   PLUGIN ENCLUME GUI DE RITO | CONFIG
#============================================================================================================
#
#
#               _______   __________    __  ____  _________       ________  ______
#              / ____/ | / / ____/ /   / / / /  |/  / ____/      / ____/ / / /  _/
#             / __/ /  |/ / /   / /   / / / / /|_/ / __/        / / __/ / / // /
#            / /___/ /|  / /___/ /___/ /_/ / /  / / /___       / /_/ / /_/ // /
#           /_____/_/ |_/\____/_____/\____/_/  /_/_____/       \____/\____/___/
#
#
#   - github: https://github.com/RitoOFF
#   - youtube: https://www.youtube.com/@RitoOFF/featured
#   - discord: rito.off
#
#============================================================================================================
#                                   PLUGIN ENCLUME GUI DE RITO | CONFIG
#============================================================================================================
#
#
#
#
#-----------------------------------------------------------------------------------------------------------
#                                           MESSAGE
#-----------------------------------------------------------------------------------------------------------
message.no-item: "§r§e§l> §r§fVous devez avoir §eune piece d'armure§f/§eun outils§f/§eune épée§f dans la main afin d'utiliser l'enclume"
message.no-money: "§r§e§l> §r§fVous devez avoir §e10 dollard !"
message.no-xp: "§r§e§l> §r§fVous devez avoir §e10 level d'xp !"
#
#-----------------------------------------------------------------------------------------------------------
#                                           XP
#-----------------------------------------------------------------------------------------------------------
xp-enclume: true # si vous metez pour le systeme avec l'argent mettez false et true pour economy api
prix.repair-xp: 2 # En level
#
#
#-----------------------------------------------------------------------------------------------------------
#                                           ARGENT
#-----------------------------------------------------------------------------------------------------------
economyapi: false # si vous metez pour le systeme avec l'xp mettez false et true pour xp enclume

prix.repair-money: 10